name: Validate OpenAPI Document

on:
  push:
    paths:
      - openapi/**
      - .github/workflows/openapi-validate.yaml
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Validate
        run: |
          cd openapi
          ./bundle.sh
          git diff --exit-code --name-only
          ./validate.sh
